name: Build

on: [push, pull_request]

jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install gcc-12 g++-12
    - name: CMake configure
      run: >
        cmake -S . -B build
      env:
        CC: gcc-12
        CXX: g++-12
    - name: Build
      run: |
        cmake --build build
      env:
        CC: gcc-12
        CXX: g++-12

  ubuntu-clang-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install clang-17
    - name: CMake configure
      run: >
        cmake -S . -B build
      env:
        CC: clang
        CXX: clang++
    - name: Build
      run: |
        cmake --build build
      env:
        CC: clang-17
        CXX: clang++-17