name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: '.'
          clangFormatVersion: 17

  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install cppcheck
        sudo apt-get install valgrind
        sudo apt-get install gcc-12 g++-12
    - name: CMake configure
      run: |
        cmake -S . -B build \
        -D ENABLE_TESTS=ON \
        -D CMAKE_BUILD_TYPE=Release
      env:
        CC: gcc-12
        CXX: g++-12
    - name: Build
      run: |
        cmake --build build --config Release --parallel
      env:
        CC: gcc-12
        CXX: g++-12
    - name: Run tests
      shell: bash
      run: |
        ./bin/tests/arith_ops_test
        ./bin/tests/math_func_test

  ubuntu-clang-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install cppcheck
        sudo apt-get install valgrind
        sudo apt-get install clang-15
    - name: CMake configure
      run: |
        cmake -S . -B build \
        -D ENABLE_TESTS=ON \
        -D CMAKE_BUILD_TYPE=Release
      env:
        CC: clang-15
        CXX: clang++-15
    - name: Build
      run: |
        cmake --build build --config Release --parallel
      env:
        CC: clang-15
        CXX: clang++-15
    - name: Run tests
      shell: bash
      run: |
        ./bin/tests/arith_ops_test
        ./bin/tests/math_func_test

  windows-msvc-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: CMake configure
        shell: bash
        run: |
          cmake -S . -B build \
          -D ENABLE_TESTS=ON \
          -D CMAKE_BUILD_TYPE=Release
      - name: Build
        shell: bash
        run: |
          cmake --build build --config Release --parallel
      - name: Run tests
        shell: bash
        run: |
          ./bin/tests/arith_ops_test
          ./bin/tests/math_func_test
